title: NDP2022
url: ""
favicon: /images/NDP22 Logo Small.png
colors:
  primary-color: "#EE3E35"
  secondary-color: "#EE3E35"
  media-colors:
    - title: media-color-one
      color: "#ee3e35"
    - title: media-color-two
      color: "#ee3e35"
    - title: media-color-three
      color: "#ee3e35"
    - title: media-color-four
      color: "#ee3e35"
    - title: media-color-five
      color: "#ee3e35"
resources_name: Resources
description: This year’s theme reinforces the value of strength in unity. The
  importance of family and community as we strive toward a stronger future
  together.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://mindef-ndp2022-staging.netlify.app
prod: https://mindef-ndp2022-prod.netlify.app
shareicon: /images/About - Theme and Logo Image 20May2022 12pm.jpg
google_analytics: UA-231714421-1
